### ISSUE TITLE
Download management can not install apk

### ISSUE THREAD

**Issue by AcAugus** [hazuki0x0/YuzuBrowser#6] opened 2017-09-04 08:56 UTC
Download management can not install apk

**Comment by hazuki0x0** [comment] 2017-09-13 11:20
1. What is the android version, device, and browser version?
2. What is the situation like?

**Comment by JWGavin** [comment] 2017-09-14 09:14
1、android 6.0
2、Click apk in the download list , But the show can not find the installer

**Comment by hazuki0x0** [comment] 2017-09-22 13:48
In my environment, this phenomenon was not produced.
The extension may be incorrect.

**Comment by meDevil** [comment] 2017-10-05 16:56
i have the same problem, android 5.1

**Comment by hazuki0x0** [comment] 2017-10-07 14:15
What device?
Does it occur on all pages or specific pages?
Can you send the problem page url?

**Comment by Viqsi** [comment] 2017-11-03 12:00
Same issue here.
Device is a Samsung Galaxy Note 4 (SM-N910C) running Android 6.0.1.
Experienced this phenomenon on https://forum.xda-developers.com/showthread.php?t=3034811 - the first post in this thread has an attached APK (the Xposed Installer). Attempting to select this APK in the download list does not start the application installer. Navigating to the download directory using a file browser and opening the APK that way works just fine, so the APK itself is fine; it's just attempting to launch it from Yuzu that is affected.

Hope this helps (and keep up the good work!).

**Comment by hazuki0x0** [comment] 2017-11-18 06:12
Thank you for the detailed information. However, I did not reproduce it on my devices or emulator.
I'm proceeding to identify the cause of this bug.

**Comment by hazuki0x0** [comment] 2018-01-17 14:52
The bug is probably fixed in 470b5d7a04809ba7d03282e546f84c1a533f8376 (ver 4.0.2).

**Closed** 2018-01-27 07:40 UTC

**Comment by meDevil** [comment] 2018-04-01 10:17
it fixed now👍
